title: Jia Zhang (张佳), Ph.D. Candidate at Xiamen University (Since 2016)
url: "jiazhang-ml.pub/"

#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "jiazhang-ml.pub/"
# footer_text: "Web: jiazhang-ml.pub (Last updated: July 15 2019)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 #- name: "Resume"
 #  link: "resume.pdf"
 #- name: "Contact"
 #  link: "contact"
