title: Jia Zhang (张佳), Jinan University|Guangzhou
url: "jiazhang-ml.github.io/"

#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "jiazhang-ml.github.io/"
# footer_text: "Web: jiazhang-ml.pub (Last updated: July 15 2019)"

sass:
    style: compressed
    sass_dir: _sass

nav:

 - name: "Homepage"
   link: "index"
 - name: "Chinese Resume"
   link: "ch-resume"
 - name: "Contact"
   link: "contact"
